### ISSUE TITLE
Can‘t be deployed  to cloudflare？

### ISSUE THREAD

**Issue by abcpeak** [onwidget/astrowind#149]
I deploye it to cloudflare，through it display sucss ,  I can’t open the site. I tried 3 times  and don't know why...

```
Success: Finished cloning repository files
No build command specified. Skipping build step.
Note: No functions dir at /functions found. Skipping.
Validating asset output directory
Deploying your site to Cloudflare's global network...
 Uploading... (99/99)

✨ Success! Uploaded 0 files (99 already uploaded) (0.42 sec)

✨ Upload complete!
Success: Assets published!
Success: Your site was deployed!
Deploying your site to Cloudflare's global network...
 Uploading... (99/99)

✨ Success! Uploaded 0 files (99 already uploaded) (0.42 sec)

✨ Upload complete!
```

**Comment by vtisnado** [comment]
I was able to deploy to Cloudflare Pages, just choose **AstroJS** in the framework preset and add the build command: `npm run build`. I'm using Bun, so that's why I have `bun run build ` in the framework preset.

Also make sure to update AstroJS to the latest version.

<img width="489" alt="Screenshot 2024-01-23 at 11 29 54 AM" src="https://github.com/onwidget/astrowind/assets/1319443/f6cc0cd6-4fa6-4d0e-98c9-bdfd4d614c05">
