### ISSUE TITLE
Regular expression error occurs when "tags" into md file in CJK language is specified

### ISSUE THREAD

**Issue by nemu1113** [onwidget/astrowind#20]
Hello, thank you so much for developing this wonderful theme.
I will tell you that I detected one problem in touching this theme.

The following error occurs when CJK language keywords are entered for "tags" in markdown files.
※CJK: Chinese、Japanese、Korean

### Target file path
```
/
├── src/
│   ├── data/
|   |   └── posts/
|   |       ├── post-slug-1.md
```

### Error log text
``` console
 error   Expected "tag" to match "[^\/#\?]+?", but got ""
TypeError: Expected "tag" to match "[^\/#\?]+?", but got ""
    at Object.generate (.\astrowind-main\node_modules\path-to-regexp\dist\index.js:229:27)    
    at file://astrowind-main/node_modules/astro/dist/core/render/paginate.js:41:35
    at Array.map (<anonymous>)
    at paginateUtility (file://astrowind-main/node_modules/astro/dist/core/render/paginate.js:20:48)
    at ./astrowind-main/src/pages/[...tags]/[tag]/[...page].astro:1:3
    at Array.map (<anonymous>)
    at Module.getStaticPaths (./astrowind-main/src/pages/[...tags]/[tag]/[...page].astro:1:3) 
    at async callGetStaticPaths (file://astrowind-main/node_modules/astro/dist/core/render/route-cache.js:20:18)
    at async getParamsAndProps (file://astrowind-main/node_modules/astro/dist/core/render/core.js:22:25)
    at async matchRoute (file://astrowind-main/node_modules/astro/dist/vite-plugin-astro-server/index.js:171:33)
```

### Theme Version
0.2.0

### Are you adding other plugins, integrations etc.?
No

**Comment by prototypa** [comment]
Hello @nemu1113, 

Thank you very much for bringing this topic.

I had not realized it, the problem is that internally I'm using `slugify` and it removes several characters, including asian characters. For now I saw that there is a library that claims to do the same as `slugify` but respecting the Asian characters:

https://github.com/jeremys/uslug

In the meantime you could try substituting `slugify` for `uslug` and see how it goes.

As soon as I have an update in the library I will let you know.

**Comment by prototypa** [comment]
Hello @nemu1113, 

Thank you very much for bringing this topic.

I had not realized it, the problem is that internally I'm using `slugify` and it removes several characters, including CJK characters. For now I saw that there is a library that claims to do the same as `slugify` but respecting the CJK characters:

https://github.com/jeremys/uslug (archived)

In the meantime you could try substituting `slugify` for `uslug` and see how it goes.

As soon as I have an update in the library I will let you know.

**Comment by prototypa** [comment]
@nemu1113, I find another library

> This module extends the fantastic [speakingurl](https://www.npmjs.com/package/speakingurl) module to include Romanisation of Chinese and Japanese scripts.

https://github.com/lovell/limax

Currently supports, but not limited to, the following scripts:

- Latin: e.g. English, français, Deutsch, español, português
- Cyrillic: e.g. Русский язык, български език, українська мова
- Chinese: e.g. 官话, 吴语 (converts to Latin script using Pinyin with optional tone number)
- Japanese: e.g. ひらがな, カタカナ (converts to Romaji using Hepburn)

Examples:
```javascript
const latin = slug('i ♥ latin'); // i-love-latin
const cyrillic = slug('Я люблю русский'); // ya-lyublyu-russkij
const pinyin = slug('我爱官话'); // wo3-ai4-guan1-hua4
const romaji = slug('私は ひらがな が大好き'); // ha-hiragana-gaki
```

I don't know if this could work for you. Please tell me, in case you find this library useful to apply to slugs, then I'll make the changes to **AstroWind**.

**Comment by prototypa** [comment]
**UPDATE**

Hi @nemu1113,  
I already migrated from slugify to [limax](https://github.com/lovell/limax). You can clone the project and test if this way works for you.

And please let me know. I'm ignorant about CKJ languages, I'm just documenting myself. Your feedback would be very useful.

**Comment by nemu1113** [comment]
Hi @prototypa,
Thanks for your quick response on the library migration from slugify to limax!

We have Git-pulled it again and confirmed with the same sample article that the said error has been resolved and the slug generation is successful for CJK languages as well.

However, I think I need to specify some options or add encoding to the input string to make the expected slug, so I will continue my own research and investigation.

I will continue to investigate and consider this matter on my own.
Thank you again.
