### ISSUE TITLE
Dependency astro-compress unavailable

### ISSUE THREAD

**Issue by JPVan** [onwidget/astrowind#208]
```
$ pnpm i
ERR_PNPM_NO_VERSIONS  No versions available for astro-compress. The package may be unpublished.
```

Also, getting a 404 here: https://www.npmjs.com/package/astro-compress

**Comment by JPVan** [comment]
Here's why: https://github.com/astro-community/astro-compress/issues/163

> [ToxiWoxi](https://github.com/ToxiWoxi) commented [7 hours ago](https://github.com/astro-community/astro-compress/issues/163#issuecomment-1666774529) • 
> The author closed their NPM account; they'll make a new one shortly https://github.com/astro-community/astro-compress/issues/162

**Comment by prototypa** [comment]
Thanks @JPVan

Because `astro-compress` in **AstroWind** only minifies the html and css, but since in most servers the content is compressed with (gzip, brotli ...), there won't be any major effect on performance. We are going to do an in-depth study of the best current alternatives for it.

https://github.com/widgeter/astrowind/commit/ff38a2cdac5f05b6ba7b69b625aab09879e69c85

**Comment by prototypa** [comment]
Thanks @JPVan

Because `astro-compress` in **AstroWind** only minifies the html and css, but since in most servers the content is compressed with (gzip, brotli ...), there won't be any major effect on performance. We are going to do an in-depth study of the best current alternatives for it.
