### ISSUE TITLE
using vue

### ISSUE THREAD

**Issue by SyDant** [onwidget/astrowind#274]
anyone can provide how to start using vue > astro 3.0 with astrowind template ?
i still getting error and confusing every first setup 

i'm sorry i still beginner

**Comment by prototypa** [comment]
We have received this question several times. Maybe your problem is something else, we will talk about it, but just in case, it seems to me that there is a problem when the Vue integration is installed in Astro automatically using this commands:

```
npx astro add vue
```

It seems that in this process all the dependencies are uninstalled and then when you want to run the project it doesn't work. I have noticed that if after the previous command you do an installation again, then everything works:

```
npm i
```

Another alternative may be to install vue manually as the guide explains: https://docs.astro.build/en/guides/integrations-guide/vue/#install-dependencies-manually

Please let me know if everything is mixed up with this or else to continue investigating. In my environment it works without problems. Thank you.
