### ISSUE TITLE
Issue with Open Graph Image Preview Display on Whatsapp (Android and desktop).

### ISSUE THREAD

**Issue by mauriziocalarese** [onwidget/astrowind#298]
**Description:**

Hello everyone,

I am encountering an issue with the display of Open Graph image previews only on Whatsapp (Android).

I have noticed that this issue does not occur on iPhone or other platforms such as Telegram, WhatsApp, etc.

The issue seems to be related to the absence of quotation marks in the meta tags (sounds weird, but it's the only way to get it working). 

Currently, my Open Graph image meta tag is as follows:

```html
<meta content=https://mydomain.com/_astro/NzQ2JCr_yGQj_goGyCAiY3Zp5xQ2oUpNnGW382A9DxM_1y0wJq.webp property=og:image />
```

However, to resolve the issue on Android, I would like it to be:

```html
<meta content="https://mydomain.com/_astro/NzQ2JCr_yGQj_goGyCAiY3Zp5xQ2oUpNnGW382A9DxM_1y0wJq.webp" property="og:image" />
```

I saw that is generated from a library, Astrolib/seo.

Any help on how to resolve this issue would be greatly appreciated.

Thank you in advance for your time and assistance.

Cheers 😊

**Comment by prototypa** [comment]
Hi @mauriziocalarese 

This issue makes a lot of sense.

I never saw it at the time and then you closed it. We were very busy with a very complex project we had.

For now we have fixed it by disabling `astro-compress` HTML compression. There is a bug in some `astro-compress` update or in `html-minifier-terser` so the setting `removeAttributeQuotes: false` is not working.

I will let those dependencies know of the problem and when everything is ok we return to the previous configuration in **AstroWind**. For now it is not so important because _Astro_ also compresses HTML. What is lost from compressing now is the inline js and css within that HTML (which if compressed correctly with `astro-compress`)

**Comment by mauriziocalarese** [comment]
Hi @prototypa,

As you mentioned, the issue stemmed from HTML compression. I addressed it temporarily by disabling this feature globally.

Appreciate your prompt response! 🚀
