### ISSUE TITLE
how to prevent auto translation for my arabic tags

### ISSUE THREAD

**Issue by abdelkareemkobo** [onwidget/astrowind#304]
I have configured an astrowind template for my blog but when i write an Arabic article the tag go from "الدمام" into aldmam!
who to solve this problem!

**Comment by abdelkareemkobo** [comment]
@prototypa can you read this issue where they solve it but i don't know what should i  change now in my astrowind theme!
[issue](https://github.com/simov/slugify/issues/100)
it's a really quick one, thanks in advance

**Comment by abdelkareemkobo** [comment]
@prototypa  Is there any update for this problem! i have built the website and host it but just can't solve this problem! and it prevents me from building the other website with this cool theme!

**Comment by abdelkareemkobo** [comment]
@prototypa here is my solution
```javascript
export const cleanSlug = (text = '') => {
  const regex = /[^\d\u0621-\u064A]+/g;

  return trimSlash(text)
    .split('/')
    .map((slug, index, array) => {
      // Preserve slashes in the middle, but replace in the beginning and end
      if (index !== 0 && index !== array.length - 1) {
        return slug;
      }

      // If the slug starts with "-", consider it as a tag and preserve it
      if (slug.startsWith('-')) {
        return slug;
      }

      // Otherwise, replace unwanted characters
      return slug.replace(regex, '-');
    })
    .join('/');
};
```
I don't know if it the right way to solve it but i works! 
the only thing that is wrong is with the 
![image](https://github.com/onwidget/astrowind/assets/72500236/3399f386-a032-428b-ace0-13a0f0d2802c)
is the  /-/ should be the word "tag"

**Comment by prototypa** [comment]
Hi @abdelkareemkobo 

Sorry for the delay.

Another thing you can do is go to this line:

https://github.com/onwidget/astrowind/blob/155a602203167d73bc8de5c87fcf1697abe63fb7/src/utils/blog.ts#L64

and instead of using `cleanSlug`, create a new function `cleanTagSlug` that cleans up the slug for the tags a bit, (for example, replaces the spaces with '-' or whatever you need). In simpler case remove the call to the `cleanSlug` function
