### ISSUE TITLE
Cloudflare pages builds are failing:  munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by redvisual** [onwidget/astrowind#314]
Hello,

I've been using your template for a side project and deploying it via Cloudflare Pages, which has been performing exceptionally well. However, I encountered an issue yesterday as the builds began failing, prompting the following error. Interestingly, the local build process remains unaffected. Could this be attributed to a Cloudflare-related issue or potentially a dependency problem?

![error-cloudflare](https://github.com/onwidget/astrowind/assets/30594793/0bb96391-ffbe-4a16-9de9-1324c604b4d9)

Thank you.

**Comment by soranauts** [comment]
Is it maybe related to #313

**Comment by Dacong-wu** [comment]
azure and render have the same problem

**Comment by Dacong-wu** [comment]
please Squoosh
[astro-doc](https://docs.astro.build/zh-cn/guides/images/#%E9%BB%98%E8%AE%A4%E5%9B%BE%E5%83%8F%E6%9C%8D%E5%8A%A1)

**Comment by sreejithkalarikkal** [comment]
> Hello,
> 
> I've been using your template for a side project and deploying it via Cloudflare Pages, which has been performing exceptionally well. However, I encountered an issue yesterday as the builds began failing, prompting the following error. Interestingly, the local build process remains unaffected. Could this be attributed to a Cloudflare-related issue or potentially a dependency problem?
> 
> ![error-cloudflare](https://private-user-images.githubusercontent.com/30594793/290605065-0bb96391-ffbe-4a16-9de9-1324c604b4d9.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzE3NTQsIm5iZiI6MTcwMjYzMTQ1NCwicGF0aCI6Ii8zMDU5NDc5My8yOTA2MDUwNjUtMGJiOTYzOTEtZmZiZS00YTE2LTlkZTktMTMyNGM2MDRiNGQ5LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMmQzM2ZhZGI3NzBlYmY2ZWE4MThkZTA0NmRkYjBiMmM5OTg3ZDAwZWYzODEwNTM0ZDY2ZjBiNTQ2MGRjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Opk_Bv3FrffqSB7lldtx5xQHGVoAtplICCH4Fq9v96U)
> 
> Thank you.

Use pnpm install and pnpm run build ,pnpm run dev

**Comment by orpheuslummis** [comment]
having the same issue on Vercel

**Comment by codywilliamson** [comment]
same issue on Netlify, using squoosh worked for me as well.

**Comment by orpheuslummis** [comment]
Using Astro on Vercel requires a special setup https://vercel.com/docs/frameworks/astro

**Comment by whb** [comment]
same issue on Netlify
==========================================================
9:16:22 AM:  generating optimized images 
9:16:22 AM: munmap_chunk(): invalid pointer
9:16:23 AM: Aborted (core dumped)
9:16:23 AM: ​
9:16:23 AM: "build.command" failed                                        
9:16:23 AM: ────────────────────────────────────────────────────────────────
9:16:23 AM: ​
9:16:23 AM:   Error message
9:16:23 AM:   Command failed with exit code 134: npm run build (https://ntl.fyi/exit-code-134)
9:16:23 AM: ​
9:16:23 AM:   Error location
9:16:23 AM:   In build.command from netlify.toml:
9:16:23 AM:   npm run build
9:16:23 AM: ​
9:16:23 AM:   Resolved config
9:16:23 AM:   build:
9:16:23 AM:     command: npm run build
9:16:23 AM:     commandOrigin: config
9:16:23 AM:     processing:
9:16:23 AM:       html:
9:16:23 AM:         pretty_urls: false
9:16:23 AM:     publish: /opt/build/repo/dist
9:16:23 AM:     publishOrigin: config
9:16:23 AM:   headers:
9:16:23 AM:     - for: /assets/*
      values:
        Cache-Control: public, max-age=31536000, immutable
  headersOrigin: config
9:16:23 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
9:16:23 AM: Failing build: Failed to build site
9:16:24 AM: Finished processing build request in 59.17s
9:16:23 AM: Failed during stage "building site": Build script returned non-zero exit code: 2

**Comment by alelotti96** [comment]
Could anyone explain the steps to use squoosh if this solves the issue?

**Comment by soranauts** [comment]
> Could anyone explain the steps to use squoosh if this solves the issue?

I removed astro-compress from dependencies and config file. You can find configuration details for Squoosh [here](https://docs.astro.build/en/guides/images/#configure-squoosh).

**Comment by elsaso** [comment]
I was able to resolve this by using 

`  "resolutions": {
    "astro/sharp": "0.33.1",
    "astro-compress/sharp": "0.33.1"
  }
  `

**Comment by prototypa** [comment]
Hi @redvisual, @soranauts, @Dacong-wu, @sreejithkalarikkal, @orpheuslummis, @whb, @alelotti96 and @elsaso 

Thank you for this. I've been checking and it seems that it is an existing problem with the latest version of Sharp. These two tickets from the respective Sharp and Vercel repositories are reviewing the issue. In addition, there are many forums talking about Sharp failures on other platforms.

https://github.com/lovell/sharp/issues/3870
https://github.com/vercel/nft/issues/371

@elsaso, I also tried your solution but it does not solve all platforms (for example, not with Vercel)

For now we have temporarily removed astro-compress and also migrated from Sharp to Squoosh. As soon as we have a clear solution for Sharp we will revert the changes.

If you have any more problems, please let me know.
Thanks
