### ISSUE TITLE
Viewtransitions break anchor links

### ISSUE THREAD

**Issue by heesters** [onwidget/astrowind#368]
Hi, enabling viewtransitions breaks anchor links (redirect to certain spot on page). This does not happen with nom run dev but it does when I build my static site.
Any ideas?
Thanks!

**Comment by heesters** [comment]
gitlab pages deployment btw.

**Comment by prototypa** [comment]
Hi @heesters 

I have tested AstroWind with `ViewTransitions` and see that everything works fine, including the anchor links.

Can you give me more details please?

(For the gitlab deployment, did you update the base config in [config.yaml](https://github.com/onwidget/astrowind/blob/main/src/config.yaml#L4)?)

I await your response, I am going to close this issue but as soon as we have more evidence I will open it and we will continue reviewing, Thank you.

**Comment by heesters** [comment]
> Hi @heesters
> 
> I have tested AstroWind with `ViewTransitions` and see that everything works fine, including the anchor links.
> 
> Can you give me more details please?
> 
> (For the gitlab deployment, did you update the base config in [config.yaml](https://github.com/onwidget/astrowind/blob/main/src/config.yaml#L4)?)
> 
> I await your response, I am going to close this issue but as soon as we have more evidence I will open it and we will continue reviewing, Thank you.

Hello,
I've been trying to troubleshoot this issue myself without succes.
Basically, I have a page about.astro with some anchors 
`{
          text: 'Team',
          href: getPermalink('/about#team'),
        },`
This works without view transitions, it works with view transitions if I run npm run dev, but it doesn't work when I deploy my static site.
My config is:
  site: 'https://site.gitlab.io'
  base: '/'
  trailingSlash: false

Is there anything else I can provide to help you help me? thanks!

**Comment by prototypa** [comment]
Hi @heesters 

We have activated `ViewTransitions` by default in **AstroWind**.

We will do a detailed review of the problem you mention and let you know. We reopened this issue.
Thank you.

**Comment by prototypa** [comment]
Hi @heesters 

In **AstroWind**, as I said, we have activated `ViewTransitions` by default and we also currently have a link in a similar way to how you have it in _GitLab_

- Go to https://astrowind.vercel.app/homes/personal
- Click the **_Hire Me_** button

It runs smoothly. We are suspecting that it is a _GitLab_-specific problem or perhaps a combination of some detail in **AstroWind** or _Astro_ that manifests itself poorly in _GitLab_.

Researching on the internet I have found that there are problems in GitLab when it comes to managing relative links. Maybe that's why the ViewTransitions break at some point:

- https://github.com/vercel/next.js/discussions/26231
- https://docs.gitlab.com/ee/user/project/pages/introduction.html#broken-relative-links

> GitLab Pages supports extensionless URLs. However, due to the problem described in [issue #354](https://gitlab.com/gitlab-org/gitlab-pages/-/issues/354), if an extensionless URL ends in a forward slash (/), it breaks any relative links on the page.

We leave you that clue and let us know if you discover anything, for now we are going to close this issue again since we have not found anything significant.

**Comment by heesters** [comment]
Hi @prototypa ,
I found a hacky solutions, which could maybe be incorporated in getstaticpath.
I changed my navigation to: `{ text: 'Team', href: getPermalink('/about/index.html#team'), },`
Would you expect any problems with this?

**Comment by heesters** [comment]
I found a better solution, maybe you can look into it for V2:

document.addEventListener('astro:after-swap', () => {
        const hash = window.location.hash;
        if (hash) {
          // Scroll to the element after client-side navigation
          const target = document.querySelector(hash);
          if (target) {
            target.scrollIntoView({ behavior: 'smooth' });
          }
        }
      });
