### ISSUE TITLE
header in article with mdx is broken

### ISSUE THREAD

**Issue by diomed** [onwidget/astrowind#402]
there is something wrong with fixed header navigation in:
https://astrowind.vercel.app/markdown-elements-demo-post

apparently does not have that white background, usually present otrherwise.

**Comment by prototypa** [comment]
Hi @diomed 

Now it is solved but the problem has to do with the fact that by default the images that appear in the articles if they are inserted as Markdown are not lazy.  A simple way to solve this is to make all articles of type MDX and instead of putting the Markdown tag for images, instead import and use the Images component.  We are reviewing what to do internally so that by default any image inserted using Markdown is lazy.  Maybe we'll make a Markdown plugin for that.  Thank you

**Comment by prototypa** [comment]
Hi @diomed 

Fixed with: 
- https://github.com/onwidget/astrowind/commit/05412477c723dbfe357386307942c4cdb0f4ba4d

Thanks
