### ISSUE TITLE
Make repository a GitHub Template Repository

### ISSUE THREAD

**Issue by asheliahut** [onwidget/astrowind#403]
By making this "template" repository into a true GitHub template repository it can allow for developers to quickly pull this code and track updates from their own repository without dealing with fork problems. All the benefits of making it a true [GitHub Template Repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) can be found from the link. 

The change to allow for this functionality is as simple as hitting a checkbox from within GitHub settings under General.

![image](https://github.com/onwidget/astrowind/assets/945619/d81038cd-6121-4db1-ae3f-33c7e2481cbf)

I believe this can make for a more robust experience for the users of the template on new projects.

**Comment by prototypa** [comment]
Hi @asheliahut 

Thanks for the idea. A few months ago we had it as well as Github Template Repository. However, at one point in history we started working on a UI similar to the one Vercel has to start a project through a base project, but adding a specific settings configuration. That's why we closed the Github Template Repository here. But along the way we found some bugs in that interface that we must correct before bringing it to light and other work took up our time and it has stayed that way. We have converted it back to Template Repository until further notice. 

I hope it is useful for you.

**Comment by asheliahut** [comment]
@prototypa thanks for the quick reply, I totally agree once you move in that direction, my thought is that once that is ready the documentation in the README can then be updated and can remove it once that is in place. I appreciate re adding the functionality until that is ready.
