### ISSUE TITLE
PageSpeed insight perfomance is 76, but not 100

### ISSUE THREAD

**Issue by rusakovic** [onwidget/astrowind#409]
URL: https://pagespeed.web.dev/analysis/https-astrowind-vercel-app-markdown-elements-demo-post/1ofkogcect?form_factor=mobile

![image](https://github.com/onwidget/astrowind/assets/17801144/8d73787c-8534-43f5-a5e4-2b59cd131805)
![image](https://github.com/onwidget/astrowind/assets/17801144/b3fb5f44-f064-4bf3-8d04-7c1325e55d26)

**Comment by prototypa** [comment]
Hi @rusakovic 

The homepage and almost every page has 100%. 

https://pagespeed.web.dev/analysis/https-astrowind-vercel-app/p56ytkh5ev?form_factor=mobile

![Screenshot_20240402-131552](https://github.com/onwidget/astrowind/assets/54446028/4276fa67-0f8c-44d2-9bcd-4326c8fd66d8)

Can you explain better what the goal of this?
Thanks

**Comment by prototypa** [comment]
We have noticed that the PageSpeed ​​in that particular case is related to the default way Astro includes images using Markdown code. Since that is an MDX page, you can import our `Image` component to use the images and the PageSpeed ​​will return to 100%.

A long-term alternative is for all images imported into Markdown to be lazy and optimized by default. For that we would have to work, maybe make a markdown plugin, we are not sure, we have to investigate.

**Comment by prototypa** [comment]
Hi @rusakovic 

Now this particular route has 100% Page Speed
https://pagespeed.web.dev/analysis/https-astrowind-vercel-app-markdown-elements-demo-post/xy6j4fvb24?form_factor=mobile

<img width="1455" alt="Screenshot 2024-04-02 at 2 13 10 PM" src="https://github.com/onwidget/astrowind/assets/54446028/321a3846-70c7-4af2-8a57-51f7f6cf54b5">

Thanks
