### ISSUE TITLE
inline code in 1 backtick was not converted correctly in markdown 

### ISSUE THREAD

**Issue by HelloAldis** [onwidget/astrowind#445]
Steps:
1. Use 1 backtick likes  \`code\` in markdown
2. Render markdown to web page, \`code\` was not convert to `code`, still was \`code\`  in web page
3. Is this right ？How to change it in configuration ?

**Comment by prototypa** [comment]
Hi @HelloAldis 

Your reasoning is partly right. Code is being displayed between the `` symbols, however Code is being converted to in the `<code>` tag,

<img width="1101" alt="Screenshot 2024-06-22 at 7 49 25 PM" src="https://github.com/onwidget/astrowind/assets/54446028/88bda979-19af-4022-9cf0-1c58f5f79215">

The transformation is happening correctly except that the styles are displayed with those backtick symbols. This is the default transformation of the tailwind css plugin we use:
https://github.com/tailwindlabs/tailwindcss-typography

Here is an article on how to configure the plugin to not display backticks. Its only a small configuration into `tailwind.css.js` file

https://futurestud.io/tutorials/tailwind-css-remove-backticks-around-inline-code

For now I close the issue since it is not an issue with **AstroWind**, the backtick is being converted correctly into `<code>`. We will think about whether to change the default to your style (without backtick) or leave it as is.

Thank you
